### ISSUE TITLE
When trying to run npm run dev, it fails to render the content

### ISSUE THREAD

**Issue by wickathou** [ProjectPenrose/paradox#1]
When I try running `npm run dev` to see the boilerplate code, the components are not loading and no issues are found shown on the console.

My process was:

1. `git clone git@github.com:ProjectPenrose/paradox.git`
2. `npm install`
3. `npm run dev`

I also tried running `npm run webpack` but I get the error
`> paradox@0.0.1 webpack
> ./node_modules/.bin/webpack.cmd -w

sh: 1: ./node_modules/.bin/webpack.cmd: not found`

**Comment by alexsc6955** [comment]
In paradox@0.0.1 You need to run `dev` and `webpack` in parallel. I refactored the "dev" script. Now you should be able to render without executing `npm run webpack`

Please try to pull the repository again and:

1. `npm i`
2. `npm run dev`
